[package]
org = "ballerina"
name = "udp"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["UDP", "datagram", "transport"]
repository = "https://github.com/ballerina-platform/module-ballerina-udp"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.4.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "udp-native"
version = "@toml.version@"
path = "../native/build/libs/udp-native-@project.version@.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/udp-test-utils-@project.version@.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/netty-handler-@netty.version@.jar"

[[platform.java11.dependency]]
path = "./lib/netty-buffer-@netty.version@.jar"

[[platform.java11.dependency]]
path = "./lib/netty-transport-@netty.version@.jar"

[[platform.java11.dependency]]
path = "./lib/netty-common-@netty.version@.jar"

[[platform.java11.dependency]]
path = "./lib/netty-resolver-@netty.version@.jar"
