[package]
org = "ballerina"
name = "udp"
version = "0.8.1"

[[dependency]]
org = "ballerina"
name = "io"
version = "0.5.5"

[[dependency]]
org = "ballerina"
name = "log"
version = "1.0.5"

[[platform.java11.dependency]]
path = "../udp-native/build/libs/udp-native-0.8.1-SNAPSHOT.jar"
groupId = "ballerina"
artifactId = "udp"
version = "0.8.1-SNAPSHOT"

[[platform.java11.dependency]]
path = "../udp-test-utils/build/libs/udp-test-utils-0.8.1-SNAPSHOT.jar"
groupId = "org.ballerinalang.stdlib.udp"
scope = "testOnly"
artifactId = "udp"
version = "0.8.1-SNAPSHOT"

[[platform.java11.dependency]]
artifactId = "netty-all"
version = "4.1.50.Final"
path = "./build/libs/netty-all-4.1.50.Final.jar"
groupId = "io.netty"
